### ISSUE TITLE
npm package in subfolder

### ISSUE THREAD

**Issue by Almeonamy** [MakotoAtsu/AspNetCore_Vite_Template#3]
Hello. In this template the package.json is in subfolder ClientApp.
If I add a module to package.json this module isn't installed automatically.
Visual Studio requires package.json in root folder.
How you solve this ptoblem?

**Comment by MakotoAtsu** [comment]
The package.json puts in the ClientApp folder. 
That is because the ClientApp folder is a pure frontend app, 
and You can easily replace it with another Vite template or your existing frontend app.
I usually recommend people manual to do "npm install".

Back to your problem, 
The "npm install" script only runs in the situation that there is no node_module in the ClientApp folder.
It's because I want to speed up frontend server startup time.

There are two solutions for you.
1. Check out the csproj file. You can remove the below condition if you want to run "npm install" each time you press f5 to debug. 

![image](https://user-images.githubusercontent.com/7738420/198932438-3c764b5f-2532-4956-8385-756ba1b9f8c0.png)


2. Add the below target in your csproj.
Now "npm install" will execute each time when you press the "Rebuild" button.
```
<!-- Run "npm install" before each time Rebuild -->
<Target Name="RunNpmInstallBeforeRebuild" BeforeTargets="Rebuild">
	<Message Importance="high" Text="Restoring dependencies using 'npm'. This may take several minutes..." />
	<Exec WorkingDirectory="$(SpaRoot)" Command="npm install">
		<Output TaskParameter="ExitCode" PropertyName="ErrorCode" />
	</Exec>
	<Error Condition="'$(ErrorCode)' != '0'" Text="Restore dependencies fails... please manually do it. (npm install)" />
</Target>
```

@Almeonamy 
If you feel the "Rebuild" solution can help,
maybe I will add it in the next version.
